
#
# /etc/smsd.conf
#
# Description: Main configuration file for the smsd
#

devices = GSM1
outgoing = /data/sms/outgoing
checked = /data/sms/checked
incoming = /data/sms/incoming
logfile = /var/log/smsd.log
infofile = /run/smstools/smsd.working
pidfile = /run/smstools/smsd.pid
outgoing = /data/sms/outgoing
checked = /data/sms/checked
failed = /data/sms/failed
incoming = /data/sms/incoming
sent = /data/sms/sent
stats = /data/logs/smsd_stats

executable_check = no
receive_before_send = no

incoming_utf8 = yes

status_include_counters = no
status_signal_quality = no

stats_interval = 0
stats = /data/sms/stats
loglevel = 3
whitelist = /data/sms/whitelist
#alarmhandler = /data/sms/alarmhandler

[GSM1]
device = /dev/null
baudrate = 115200
rtscts = no
incoming = yes
pin = ignore
memory_start = 0
eventhandler = /usr/bin/imonsmshandler
