
DISTRO = "imon"
DISTRO_NAME = "iMonOS"
DISTRO_VERSION = "1.0.0"

IMAGE_NAME:append = "-${DISTRO}-${DISTRO_VERSION}"

PACKAGE_CLASSES = "package_deb"

DEFAULT_TIMEZONE = "Europe/Warsaw"

GLIBC_GENERATE_LOCALES = "en_US.UTF-8"
IMAGE_LINGUAS ?= "en-us"

DISTRO_FEATURES:remove = " \
	x11 \
	wayland \
	pulseaudio \
	directfb \
	bluetooth \
	irda \
	nfs \
	alsa \
	ipv6 \
	phone \
	ipsec \
	nfc \
	smbfs \
	wifi \
	3g \
	"

DISTRO_FEATURES:append = " pam systemd rauc"

# Define Init System
INIT_MANAGER = "systemd"

VIRTUAL-RUNTIME_dev-manager = "udev"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"

VOLATILE_LOG_DIR = "no"

RPI_USE_U_BOOT = "1"

LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"

WIC_CREATE_EXTRA_ARGS ?= "--no-fstab-update"

ROOT_PASSWD = "\$6\$0GpXXsc/QYQql$Lrca/3.m55tK2.eaUmL9Q3enzflTKx2Bu/lu8JwvQWigqIFZaRCB5YJL164zsgxNYduYJue14muT0g.q0UR8l/"
IMON_PASSWD = "\$6\$1U9BK8qr8U5d22$Q8f4oU7UQV6KFgPWtqx1ilzh2qsn/df2Xp.y1LD5XNizUZ6z0cUy4z8laVn6B7K/zA9UcOHrldmqoO74efLn7/"

BOOT_SPACE = "1073741"
INITRAMFS_MAXSIZE = "315400"

# TODO move to machine configuration
IMAGE_BOOT_FILES:remove="Image"

LICENSE_FLAGS_ACCEPTED += " commercial license"
