
INHERIT += "imon-distro-version"

DISTRO = "imon"
DISTRO_NAME = "iMonOS"
DISTRO_VERSION = "${IMON_VERSION}"

IMAGE_NAME:append = "-${DISTRO}-${DISTRO_VERSION}"

PACKAGE_CLASSES = "package_deb"

DEFAULT_TIMEZONE = "Europe/Warsaw"

GLIBC_GENERATE_LOCALES = "en_US.UTF-8"
IMAGE_LINGUAS ?= "en-us"

DISTRO_FEATURES:remove = " \
	x11 \
	wayland \
	pulseaudio \
	directfb \
	bluetooth \
	irda \
	nfs \
	alsa \
	ipv6 \
	phone \
	ipsec \
	nfc \
	smbfs \
	wifi \
	3g \
	"

DISTRO_FEATURES:append = " pam systemd rauc"

# Define Init System
INIT_MANAGER = "systemd"

VIRTUAL-RUNTIME_dev-manager = "udev"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"

VOLATILE_LOG_DIR = "no"

RPI_USE_U_BOOT = "1"

LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"

WIC_CREATE_EXTRA_ARGS ?= "--no-fstab-update"

ROOT_PASSWD = "\$6\$xojTYfJsRyEky1\$w2AKyl0SckD1SiLMWQqTZb/3qL5hAa9DV586L2djOKTvBrdzG9sssT5mn59P4p4IBdVxcHwD1/EvOnf.DqGAd."
IMON_PASSWD = "\$6\$5Gbt7m893LScdds\$blR8OrQ1vDqkNrX70PQUCl6ww.FrWFWlFf4.RyKLZFe77tLm3L.1K6EDHLNcK2bs/f1l0LCmtN0NakuNVMi3D."

BOOT_SPACE = "1073741"
INITRAMFS_MAXSIZE = "315400"

# TODO move to machine configuration
IMAGE_BOOT_FILES:remove="Image"

LICENSE_FLAGS_ACCEPTED += " commercial license"
