
SPLASH = ""
DISABLE_SPLASH = "1"

COMMON_CONFIG = '\n\
# Enable watchdog on boot\n\
dtparam=watchdog=on\n\
'

RPI_EXTRA_CONFIG:append = '${COMMON_CONFIG}'

PREFERRED_VERSION_linux-raspberrypi ?= "6.6.%"